name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Check for API key
        run: |
          if [ -z "${{ secrets.GOOGLE_TTS_API_KEY }}" ]; then
            echo "ERROR: GOOGLE_TTS_API_KEY secret is not set in repository settings"
            exit 1
          else
            echo "API key is set and available"
          fi

      - name: Update API keys in files
        env:
          GOOGLE_TTS_API_KEY: ${{ secrets.GOOGLE_TTS_API_KEY }}
        run: |
          node update-api-key.js
          echo "API keys have been updated in the necessary files"

      - name: Verify API key replacement
        env:
          GOOGLE_TTS_API_KEY: ${{ secrets.GOOGLE_TTS_API_KEY }}
        run: |
          echo "Verifying API key replacement in files..."
          # Check if the API key is in the index.html file
          if grep -q "$GOOGLE_TTS_API_KEY" index.html; then
            echo "✅ API key found in index.html"
          else
            echo "❌ ERROR: API key NOT found in index.html"
            exit 1
          fi
          # Check if the API key is in the config.js file
          if grep -q "$GOOGLE_TTS_API_KEY" config.js; then
            echo "✅ API key found in config.js"
          else
            echo "❌ ERROR: API key NOT found in config.js"
            exit 1
          fi
          # Check that the API placeholder is gone
          if grep -q "__GOOGLE_TTS_API_KEY__" index.html; then
            echo "❌ ERROR: API key placeholder still found in index.html"
            exit 1
          else
            echo "✅ API key placeholder not found in index.html"
          fi
          echo "All verification checks passed!"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true 